#!/bin/bash
# Quick Live Test Guide for Advice Bus
# Run this to verify the Advice Bus is working with the live bot

echo "🚀 Advice Bus Live Test Guide"
echo "=========================================="
echo ""
echo "✅ Configuration Status:"
echo "   ADVICE_BUS_ENABLED=true"
echo "   ADVICE_BUS_PORT=45100"
echo "   ADVICE_MIN_CONFIDENCE=60"
echo "   ADVICE_MAX_HOLD_EXTENSION_SECS=30"
echo ""
echo "📋 Test Steps:"
echo ""
echo "1️⃣  Start the bot:"
echo "   cd /home/sol/Desktop/solana-dev/Bots/scalper-bot/execution"
echo "   ./target/release/execution-bot"
echo ""
echo "   ✅ Look for this log message:"
echo "   '✅ Advice Bus: Listening on 127.0.0.1:45100 (min confidence: 60)'"
echo ""
echo "2️⃣  Wait for bot to enter a position naturally"
echo "   (You'll see logs like '🎯 BUY SIGNAL' and '💰 BOUGHT')"
echo ""
echo "3️⃣  While position is ACTIVE, open a NEW terminal and run:"
echo ""
echo "   # Get the token mint address from bot logs (44-char base58 string)"
echo "   # Example: 9TnG7x...abc123"
echo ""
echo "   # Send ExtendHold advisory (extend hold by 20 seconds)"
echo "   python3 test_advisor.py extend_hold <TOKEN_MINT> 20 85"
echo ""
echo "   # Example with real address:"
echo "   python3 test_advisor.py extend_hold 9TnG7xQvs1234567890abcdefghijk 20 85"
echo ""
echo "4️⃣  Check bot logs for confirmation:"
echo "   You should see (every 5 seconds during extended hold):"
echo "   '🎯 ADVICE: Hold extended N more secs (confidence: 85)'"
echo ""
echo "5️⃣  Verify position holds LONGER than normal timeout"
echo "   Strategy timeout: ~600s (10 min)"
echo "   With advice: Up to 630s (10m 30s)"
echo ""
echo "=========================================="
echo ""
echo "🧪 Test Advisory Types:"
echo ""
echo "# ExtendHold - Hold token longer"
echo "python3 test_advisor.py extend_hold <MINT> 20 85"
echo ""
echo "# WidenExit - Urgent exit with higher slippage"
echo "python3 test_advisor.py widen_exit <MINT> 500 10000 90"
echo ""
echo "# LateOpportunity - Old token heating up (queued)"
echo "python3 test_advisor.py late_opportunity <MINT> 5 75"
echo ""
echo "# CopyTrade - Follow alpha wallet (queued)"
echo "python3 test_advisor.py copy_trade <MINT> <WALLET_ADDR> 95"
echo ""
echo "=========================================="
echo ""
echo "⚠️  Troubleshooting:"
echo ""
echo "If 'Advice Bus: Listening' doesn't appear:"
echo "  - Check .env has ADVICE_BUS_ENABLED=true"
echo "  - Restart the bot"
echo ""
echo "If advisory not received:"
echo "  - Ensure token mint matches EXACTLY (copy from logs)"
echo "  - Advisory must have confidence >= 60"
echo "  - Send advisory BEFORE position times out"
echo ""
echo "If hold extension doesn't work:"
echo "  - Check extension < 30 seconds (safety cap)"
echo "  - Advisory must arrive before normal timeout"
echo "  - Stop-loss ALWAYS overrides advice"
echo ""
echo "=========================================="
echo ""
echo "📊 Expected Performance:"
echo "   Entry Speed: 80-120ms (UNCHANGED - hot path untouched)"
echo "   Advisory Processing: < 50µs per monitoring tick"
echo "   Memory Overhead: 24 bytes per position"
echo ""
echo "✅ Advice Bus is READY for live testing!"
echo ""
